### ISSUE TITLE
Ошибка при удалении последней записи из вкладки

### ISSUE THREAD

**Issue by Jurrio** [jDevTeam/BeautySalon#15]
STR:
1. Запускаем приложение
2. Удаляем все объекты во вкладке

Ожидаемый результат:
Объекты удалены

Фактический результат:
Объекты удалены, но выбрасывается RuntimeException

**Comment by Jurrio** [comment]
@driversti возможно, причина в классе TabsOverviewController
191:  int selectedIndex = orderTable.getSelectionModel().getSelectedIndex();

когда нет объектов - соответственно нечего выделять. но это предположение

**Comment by driversti** [comment]
Это временное решение. ФИО сотрудника и клиента должны состоять из трёх слов, чтобы создать соответствующие объекты
Методы будут пересматриваться

**Comment by Jurrio** [comment]
Ордер ок. Что с остальными вкладками? Там такое же наблюдается, без трёх слов. :)

**Comment by driversti** [comment]
Баг пофиксил. Сначала неправильно понял. Теперь работает корректно. Проверь. Если у тебя всё ок, закрывай баг

**Comment by Jurrio** [comment]
Красаучик! Проверено, закрыто.
